version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["Dependabot"]
    reviewers: ["kilian1111010"]
    rebase-strategy: "auto"
    open-pull-requests-limit: 10
    groups:
      Patch:
        update-types: ["patch"]
      Minor:
        update-types: ["minor"]
      Major:
        update-types: ["major"]
