spring:
  application:
    name: WealthAndFinanceTracker

  datasource:
    url: jdbc:mariadb://${DB_IP}:${DB_PORT}/${DB_DATABASE}?useSSL=false
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
